name: Economy
version: '1.2'
main: fr.rudy.economy.main
api-version: '1.21'
depend: [DataBaseAPI, Vault]

commands:
  coins:
    description: Gérer l'argent des joueurs.
    usage: /<command> [give|set] <joueur> <montant>
