name: Economy
version: 1.2
main: fr.rudy.economy.Main
api-version: 1.21
depend: [DataBaseAPI, Vault]

loadbefore:
  - ShopkeepersAddon

commands:
  coins:
    description: Gérer l'argent des joueurs.
    usage: /<command> [give|set] <joueur> <montant>